/* ============================================
   COUNTRIES DATA — Maps TopoJSON names to flags
   ============================================ */

const FLAG_FOLDER = 'Alamin PNG Flags';

// Continent definitions with zoom bounding boxes [minLon, minLat, maxLon, maxLat]
const CONTINENTS = {
  world:        { name: 'World',                         emoji: '🌍', bounds: null },
  africa:       { name: 'Africa',                        emoji: '🌍', bounds: [[-22, -37], [53, 39]] },
  asia:         { name: 'Asia',                          emoji: '🌏', bounds: [[26, -12], [150, 56]] },
  oceania:      { name: 'Australia & Oceania',           emoji: '🌏', bounds: [[112, -48], [178, 2]] },
  europe:       { name: 'Europe',                        emoji: '🌍', bounds: [[-25, 34], [48, 71]] },
  northamerica: { name: 'North & Central America',       emoji: '🌎', bounds: [[-138, 5], [-52, 75]] },
  southamerica: { name: 'South America',                 emoji: '🌎', bounds: [[-83, -57], [-33, 14]] }
};

// Map from TopoJSON feature name → { flag filename, continent key, displayName }
// The TopoJSON uses Natural Earth naming conventions
const COUNTRIES_DATA = {
  // AFRICA
  "Algeria":                  { flag: "Algeria.png",                         continent: "africa",       display: "Algeria" },
  "Angola":                   { flag: "Angola.png",                          continent: "africa",       display: "Angola" },
  "Benin":                    { flag: "Benin.png",                           continent: "africa",       display: "Benin" },
  "Botswana":                 { flag: "Botswana.png",                        continent: "africa",       display: "Botswana" },
  "Burkina Faso":             { flag: "Burkina Faso.png",                    continent: "africa",       display: "Burkina Faso" },
  "Burundi":                  { flag: "Burundi.png",                         continent: "africa",       display: "Burundi" },
  "Cameroon":                 { flag: "Cameroon.png",                        continent: "africa",       display: "Cameroon" },
  "Cape Verde":               { flag: "Cape Verde.png",                      continent: "africa",       display: "Cape Verde" },
  "Central African Rep.":     { flag: "Central African Republic.png",        continent: "africa",       display: "Central African Republic" },
  "Central African Republic": { flag: "Central African Republic.png",        continent: "africa",       display: "Central African Republic" },
  "Chad":                     { flag: "Chad.png",                            continent: "africa",       display: "Chad" },
  "Comoros":                  { flag: "Comoros.png",                         continent: "africa",       display: "Comoros" },
  "Congo":                    { flag: "Congo Republic of the.png",           continent: "africa",       display: "Republic of the Congo" },
  "Dem. Rep. Congo":          { flag: "Congo Democratic Republic of the.png",continent: "africa",       display: "DR Congo" },
  "Côte d'Ivoire":            { flag: "Cote d'lvoire.png",                   continent: "africa",       display: "Côte d'Ivoire" },
  "Ivory Coast":              { flag: "Cote d'lvoire.png",                   continent: "africa",       display: "Côte d'Ivoire" },
  "Djibouti":                 { flag: "Djibouti.png",                        continent: "africa",       display: "Djibouti" },
  "Egypt":                    { flag: "Egypt.png",                           continent: "africa",       display: "Egypt" },
  "Eq. Guinea":               { flag: "Equatorial Guinea.png",               continent: "africa",       display: "Equatorial Guinea" },
  "Equatorial Guinea":        { flag: "Equatorial Guinea.png",               continent: "africa",       display: "Equatorial Guinea" },
  "Eritrea":                  { flag: "Eritrea.png",                         continent: "africa",       display: "Eritrea" },
  "eSwatini":                 { flag: "Eswatini.png",                        continent: "africa",       display: "Eswatini" },
  "Eswatini":                 { flag: "Eswatini.png",                        continent: "africa",       display: "Eswatini" },
  "Swaziland":                { flag: "Eswatini.png",                        continent: "africa",       display: "Eswatini" },
  "Ethiopia":                 { flag: "Ethiopia.png",                        continent: "africa",       display: "Ethiopia" },
  "Gabon":                    { flag: "Gabon.png",                           continent: "africa",       display: "Gabon" },
  "Gambia":                   { flag: "Gambia.png",                          continent: "africa",       display: "Gambia" },
  "Ghana":                    { flag: "Ghana.png",                           continent: "africa",       display: "Ghana" },
  "Guinea":                   { flag: "Guinea.png",                          continent: "africa",       display: "Guinea" },
  "Guinea-Bissau":            { flag: "Guinea Biisau.png",                   continent: "africa",       display: "Guinea-Bissau" },
  "Kenya":                    { flag: "Kenya.png",                           continent: "africa",       display: "Kenya" },
  "Lesotho":                  { flag: "Lesotho.png",                         continent: "africa",       display: "Lesotho" },
  "Liberia":                  { flag: "Liberia.png",                         continent: "africa",       display: "Liberia" },
  "Libya":                    { flag: "Libya (2).png",                       continent: "africa",       display: "Libya" },
  "Madagascar":               { flag: "Madagascar.png",                      continent: "africa",       display: "Madagascar" },
  "Malawi":                   { flag: "Malawi.png",                          continent: "africa",       display: "Malawi" },
  "Mali":                     { flag: "Mali.png",                            continent: "africa",       display: "Mali" },
  "Mauritania":               { flag: "Mauritania.png",                      continent: "africa",       display: "Mauritania" },
  "Mauritius":                { flag: "Mauritius.png",                       continent: "africa",       display: "Mauritius" },
  "Morocco":                  { flag: "Morocco.png",                         continent: "africa",       display: "Morocco" },
  "Mozambique":               { flag: "Mozambique.png",                      continent: "africa",       display: "Mozambique" },
  "Namibia":                  { flag: "Namibia.png",                         continent: "africa",       display: "Namibia" },
  "Niger":                    { flag: "Niger.png",                           continent: "africa",       display: "Niger" },
  "Nigeria":                  { flag: "Nigeria.png",                         continent: "africa",       display: "Nigeria" },
  "Rwanda":                   { flag: "Rwanda.png",                          continent: "africa",       display: "Rwanda" },
  "W. Sahara":                { flag: "Western Sahara.png",                  continent: "africa",       display: "Western Sahara" },
  "Western Sahara":           { flag: "Western Sahara.png",                  continent: "africa",       display: "Western Sahara" },
  "São Tomé and Príncipe":    { flag: "Sao Tome and Principe.png",           continent: "africa",       display: "São Tomé and Príncipe" },
  "Senegal":                  { flag: "Senegal.png",                         continent: "africa",       display: "Senegal" },
  "Seychelles":               { flag: "Seychelles.png",                      continent: "africa",       display: "Seychelles" },
  "Sierra Leone":             { flag: "Sierra Leone.png",                    continent: "africa",       display: "Sierra Leone" },
  "Somalia":                  { flag: "Somalia.png",                         continent: "africa",       display: "Somalia" },
  "Somaliland":               { flag: "Somaliland.png",                      continent: "africa",       display: "Somaliland" },
  "South Africa":             { flag: "South Africa.png",                    continent: "africa",       display: "South Africa" },
  "S. Sudan":                 { flag: "South Sudan.png",                     continent: "africa",       display: "South Sudan" },
  "South Sudan":              { flag: "South Sudan.png",                     continent: "africa",       display: "South Sudan" },
  "Sudan":                    { flag: "Sudan.png",                           continent: "africa",       display: "Sudan" },
  "Tanzania":                 { flag: "Tanzaniazz.png",                      continent: "africa",       display: "Tanzania" },
  "Togo":                     { flag: "Togo.png",                            continent: "africa",       display: "Togo" },
  "Tunisia":                  { flag: "Tunisia.png",                         continent: "africa",       display: "Tunisia" },
  "Uganda":                   { flag: "Uganda.png",                          continent: "africa",       display: "Uganda" },
  "Zambia":                   { flag: "Zambia.png",                          continent: "africa",       display: "Zambia" },
  "Zimbabwe":                 { flag: "Zimbabwe.png",                        continent: "africa",       display: "Zimbabwe" },

  // ASIA
  "Afghanistan":              { flag: "Afghanistan.png",                     continent: "asia",         display: "Afghanistan" },
  "Armenia":                  { flag: "Armenia.png",                         continent: "asia",         display: "Armenia" },
  "Azerbaijan":               { flag: "Azerbaijan.png",                      continent: "asia",         display: "Azerbaijan" },
  "Bahrain":                  { flag: "Bahrain.png",                         continent: "asia",         display: "Bahrain" },
  "Bangladesh":               { flag: "Bangladesh.png",                      continent: "asia",         display: "Bangladesh" },
  "Bhutan":                   { flag: "Bhutan.png",                          continent: "asia",         display: "Bhutan" },
  "Brunei":                   { flag: "Brunei.png",                          continent: "asia",         display: "Brunei" },
  "Myanmar":                  { flag: "Myanmar.png",                         continent: "asia",         display: "Myanmar" },
  "Cambodia":                 { flag: "Cambodia.png",                        continent: "asia",         display: "Cambodia" },
  "China":                    { flag: "China.png",                           continent: "asia",         display: "China" },
  "Georgia":                  { flag: "Georgia.png",                         continent: "asia",         display: "Georgia" },
  "India":                    { flag: "India.png",                           continent: "asia",         display: "India" },
  "Indonesia":                { flag: "Indonesia.png",                       continent: "asia",         display: "Indonesia" },
  "Iran":                     { flag: "Iran.png",                            continent: "asia",         display: "Iran" },
  "Iraq":                     { flag: "Iraq.png",                            continent: "asia",         display: "Iraq" },
  "Israel":                   { flag: "Israel.png",                          continent: "asia",         display: "Israel" },
  "Japan":                    { flag: "Japan.png",                           continent: "asia",         display: "Japan" },
  "Jordan":                   { flag: "Jordan.png",                          continent: "asia",         display: "Jordan" },
  "Kazakhstan":               { flag: "Kazakhstan.png",                      continent: "asia",         display: "Kazakhstan" },
  "Kuwait":                   { flag: "Kuwait.png",                          continent: "asia",         display: "Kuwait" },
  "Kyrgyzstan":               { flag: "Flag_of_Kyrgyzstan.svg.png",          continent: "asia",         display: "Kyrgyzstan" },
  "Laos":                     { flag: "Laos.png",                            continent: "asia",         display: "Laos" },
  "Lebanon":                  { flag: "Lebanon.png",                         continent: "asia",         display: "Lebanon" },
  "Malaysia":                 { flag: "Malaysia.png",                        continent: "asia",         display: "Malaysia" },
  "Maldives":                 { flag: "Maldives.png",                        continent: "asia",         display: "Maldives" },
  "Mongolia":                 { flag: "Mongolia.png",                        continent: "asia",         display: "Mongolia" },
  "Nepal":                    { flag: "Nepal.png",                           continent: "asia",         display: "Nepal" },
  "North Korea":              { flag: "Korea North.png",                     continent: "asia",         display: "North Korea" },
  "Korea, Dem. Rep.":         { flag: "Korea North.png",                     continent: "asia",         display: "North Korea" },
  "Oman":                     { flag: "Oman.png",                            continent: "asia",         display: "Oman" },
  "Pakistan":                 { flag: "Pakistan.png",                        continent: "asia",         display: "Pakistan" },
  "Palestine":                { flag: "Palestine.png",                       continent: "asia",         display: "Palestine" },
  "Philippines":              { flag: "Philippines.png",                     continent: "asia",         display: "Philippines" },
  "Qatar":                    { flag: "Qatar.png",                           continent: "asia",         display: "Qatar" },
  "Saudi Arabia":             { flag: "Saudi Arabia.png",                    continent: "asia",         display: "Saudi Arabia" },
  "Singapore":                { flag: "Singapore.png",                       continent: "asia",         display: "Singapore" },
  "South Korea":              { flag: "Korea South.png",                     continent: "asia",         display: "South Korea" },
  "Korea, Rep.":              { flag: "Korea South.png",                     continent: "asia",         display: "South Korea" },
  "Sri Lanka":                { flag: "Sri Lanka.png",                       continent: "asia",         display: "Sri Lanka" },
  "Syria":                    { flag: "Syria.png",                           continent: "asia",         display: "Syria" },
  "Taiwan":                   { flag: "Taiwan.png",                          continent: "asia",         display: "Taiwan" },
  "Tajikistan":               { flag: "Tajikistan.png",                      continent: "asia",         display: "Tajikistan" },
  "Thailand":                 { flag: "Thailand.png",                        continent: "asia",         display: "Thailand" },
  "Timor-Leste":              { flag: "East Timor.png",                      continent: "asia",         display: "Timor-Leste" },
  "East Timor":               { flag: "East Timor.png",                      continent: "asia",         display: "Timor-Leste" },
  "Turkey":                   { flag: "Turkey.png",                          continent: "asia",         display: "Turkey" },
  "Turkmenistan":             { flag: "Turkmenistan.png",                    continent: "asia",         display: "Turkmenistan" },
  "United Arab Emirates":     { flag: "United Arab Emirates.png",            continent: "asia",         display: "UAE" },
  "Uzbekistan":               { flag: "Uzbekistan.png",                      continent: "asia",         display: "Uzbekistan" },
  "Vietnam":                  { flag: "Vietnam.png",                         continent: "asia",         display: "Vietnam" },
  "Yemen":                    { flag: "Yemen.png",                           continent: "asia",         display: "Yemen" },
  "N. Cyprus":                { flag: "Turkish Republic of Northern Cyprus.png", continent: "asia",     display: "Northern Cyprus" },
  "Cyprus":                   { flag: "Cyprus.png",                          continent: "asia",         display: "Cyprus" },
  "Hong Kong":                { flag: "Hong Kong.png",                       continent: "asia",         display: "Hong Kong" },
  "Macau":                    { flag: "Macau.png",                           continent: "asia",         display: "Macau" },

  // EUROPE
  "Albania":                  { flag: "Albania..png",                        continent: "europe",       display: "Albania" },
  "Andorra":                  { flag: "Andorra.png",                         continent: "europe",       display: "Andorra" },
  "Austria":                  { flag: "Austria.png",                         continent: "europe",       display: "Austria" },
  "Belarus":                  { flag: "Belarus.png",                         continent: "europe",       display: "Belarus" },
  "Belgium":                  { flag: "Belgium.png",                         continent: "europe",       display: "Belgium" },
  "Bosnia and Herz.":         { flag: "Bosnia and Herzegovina.png",          continent: "europe",       display: "Bosnia and Herzegovina" },
  "Bosnia and Herzegovina":   { flag: "Bosnia and Herzegovina.png",          continent: "europe",       display: "Bosnia and Herzegovina" },
  "Bulgaria":                 { flag: "Bulgaria.png",                        continent: "europe",       display: "Bulgaria" },
  "Croatia":                  { flag: "Croatia.png",                         continent: "europe",       display: "Croatia" },
  "Czechia":                  { flag: "Czech Republic.png",                  continent: "europe",       display: "Czech Republic" },
  "Czech Republic":           { flag: "Czech Republic.png",                  continent: "europe",       display: "Czech Republic" },
  "Denmark":                  { flag: "Denmark.png",                         continent: "europe",       display: "Denmark" },
  "Estonia":                  { flag: "Estonia.png",                         continent: "europe",       display: "Estonia" },
  "Finland":                  { flag: "Finland.png",                         continent: "europe",       display: "Finland" },
  "France":                   { flag: "France.png",                          continent: "europe",       display: "France" },
  "Germany":                  { flag: "Germany..png",                        continent: "europe",       display: "Germany" },
  "Greece":                   { flag: "Greece.png",                          continent: "europe",       display: "Greece" },
  "Hungary":                  { flag: "Hungary.png",                         continent: "europe",       display: "Hungary" },
  "Iceland":                  { flag: "Iceland.png",                         continent: "europe",       display: "Iceland" },
  "Ireland":                  { flag: "Ireland.png",                         continent: "europe",       display: "Ireland" },
  "Italy":                    { flag: "Italy.png",                           continent: "europe",       display: "Italy" },
  "Kosovo":                   { flag: "Kosovo.png",                          continent: "europe",       display: "Kosovo" },
  "Latvia":                   { flag: "Latvia.png",                          continent: "europe",       display: "Latvia" },
  "Liechtenstein":            { flag: "Liechtenstein.png",                   continent: "europe",       display: "Liechtenstein" },
  "Lithuania":                { flag: "Lithuania.png",                       continent: "europe",       display: "Lithuania" },
  "Luxembourg":               { flag: "Luxembourg.png",                     continent: "europe",       display: "Luxembourg" },
  "North Macedonia":          { flag: "Macedonia.png",                      continent: "europe",       display: "North Macedonia" },
  "Macedonia":                { flag: "Macedonia.png",                      continent: "europe",       display: "North Macedonia" },
  "Malta":                    { flag: "Malta.png",                           continent: "europe",       display: "Malta" },
  "Moldova":                  { flag: "Moldova.png",                        continent: "europe",       display: "Moldova" },
  "Monaco":                   { flag: "Monaco.png",                         continent: "europe",       display: "Monaco" },
  "Montenegro":               { flag: "Montenegro.png",                     continent: "europe",       display: "Montenegro" },
  "Netherlands":              { flag: "Netherlands.png",                     continent: "europe",       display: "Netherlands" },
  "Norway":                   { flag: "Norway.png",                         continent: "europe",       display: "Norway" },
  "Poland":                   { flag: "Poland.png",                         continent: "europe",       display: "Poland" },
  "Portugal":                 { flag: "Portugal.png",                        continent: "europe",       display: "Portugal" },
  "Romania":                  { flag: "Romania.png",                        continent: "europe",       display: "Romania" },
  "Russia":                   { flag: "Russia.png",                          continent: "europe",       display: "Russia" },
  "San Marino":               { flag: "San Marino.png",                     continent: "europe",       display: "San Marino" },
  "Serbia":                   { flag: "Serbia.png",                          continent: "europe",       display: "Serbia" },
  "Slovakia":                 { flag: "Slovakia.png",                        continent: "europe",       display: "Slovakia" },
  "Slovenia":                 { flag: "Slovenia.png",                        continent: "europe",       display: "Slovenia" },
  "Spain":                    { flag: "Spain.png",                           continent: "europe",       display: "Spain" },
  "Sweden":                   { flag: "Sweden.png",                          continent: "europe",       display: "Sweden" },
  "Switzerland":              { flag: "Switzerland.png",                     continent: "europe",       display: "Switzerland" },
  "Ukraine":                  { flag: "Ukraine.png",                        continent: "europe",       display: "Ukraine" },
  "United Kingdom":           { flag: "United Kigdom.png",                  continent: "europe",       display: "United Kingdom" },

  // NORTH & CENTRAL AMERICA
  "Antigua and Barbuda":      { flag: "Antigua and Barbuda.png",            continent: "northamerica", display: "Antigua and Barbuda" },
  "Bahamas":                  { flag: "Bahamas.png",                        continent: "northamerica", display: "Bahamas" },
  "Barbados":                 { flag: "Barbados.png",                       continent: "northamerica", display: "Barbados" },
  "Belize":                   { flag: "Belize.png",                         continent: "northamerica", display: "Belize" },
  "Canada":                   { flag: "Canada.png",                         continent: "northamerica", display: "Canada" },
  "Costa Rica":               { flag: "Costa Rica.png",                     continent: "northamerica", display: "Costa Rica" },
  "Cuba":                     { flag: "Cuba.png",                           continent: "northamerica", display: "Cuba" },
  "Dominica":                 { flag: "Dominica.png",                       continent: "northamerica", display: "Dominica" },
  "Dominican Rep.":           { flag: "Dominican Republic.png",             continent: "northamerica", display: "Dominican Republic" },
  "Dominican Republic":       { flag: "Dominican Republic.png",             continent: "northamerica", display: "Dominican Republic" },
  "El Salvador":              { flag: "El Salvador.png",                    continent: "northamerica", display: "El Salvador" },
  "Grenada":                  { flag: "Grenada.png",                        continent: "northamerica", display: "Grenada" },
  "Guatemala":                { flag: "Guatemala.png",                      continent: "northamerica", display: "Guatemala" },
  "Haiti":                    { flag: "Haiti.png",                          continent: "northamerica", display: "Haiti" },
  "Honduras":                 { flag: "Honduras.png",                       continent: "northamerica", display: "Honduras" },
  "Jamaica":                  { flag: "Jamaica.png",                        continent: "northamerica", display: "Jamaica" },
  "Mexico":                   { flag: "Mexico.png",                         continent: "northamerica", display: "Mexico" },
  "Nicaragua":                { flag: "Nicaragua.png",                      continent: "northamerica", display: "Nicaragua" },
  "Panama":                   { flag: "Panama..png",                        continent: "northamerica", display: "Panama" },
  "Puerto Rico":              { flag: "Puerto Rico.png",                    continent: "northamerica", display: "Puerto Rico" },
  "Saint Kitts and Nevis":    { flag: "Saint Kitts and Nevis.png",          continent: "northamerica", display: "Saint Kitts and Nevis" },
  "Saint Lucia":              { flag: "Saint Lucia.png",                    continent: "northamerica", display: "Saint Lucia" },
  "Saint Vincent and the Grenadines": { flag: "Saint Vincent and the Grenadines.png", continent: "northamerica", display: "Saint Vincent & Grenadines" },
  "Trinidad and Tobago":      { flag: "Trinidad and Tobago.png",            continent: "northamerica", display: "Trinidad and Tobago" },
  "United States of America": { flag: "United States.png",                  continent: "northamerica", display: "United States" },
  "United States":            { flag: "United States.png",                  continent: "northamerica", display: "United States" },

  // SOUTH AMERICA
  "Argentina":                { flag: "Argentina.png",                      continent: "southamerica", display: "Argentina" },
  "Bolivia":                  { flag: "Bolivia.png",                        continent: "southamerica", display: "Bolivia" },
  "Brazil":                   { flag: "Brazil.png",                         continent: "southamerica", display: "Brazil" },
  "Chile":                    { flag: "Chile.png",                          continent: "southamerica", display: "Chile" },
  "Colombia":                 { flag: "Colombia.png",                       continent: "southamerica", display: "Colombia" },
  "Ecuador":                  { flag: "Ecuador.png",                        continent: "southamerica", display: "Ecuador" },
  "Falkland Is.":             { flag: "Falkland Islands.png",               continent: "southamerica", display: "Falkland Islands" },
  "Falkland Islands":         { flag: "Falkland Islands.png",               continent: "southamerica", display: "Falkland Islands" },
  "French Guiana":            { flag: "French Guiana.png",                  continent: "southamerica", display: "French Guiana" },
  "Guyana":                   { flag: "Guyana.png",                         continent: "southamerica", display: "Guyana" },
  "Paraguay":                 { flag: "Paraguay.png",                       continent: "southamerica", display: "Paraguay" },
  "Peru":                     { flag: "Peru.png",                           continent: "southamerica", display: "Peru" },
  "Suriname":                 { flag: "Suriname.png",                       continent: "southamerica", display: "Suriname" },
  "Uruguay":                  { flag: "Uruguay.png",                        continent: "southamerica", display: "Uruguay" },
  "Venezuela":                { flag: "Venezuela.png",                      continent: "southamerica", display: "Venezuela" },

  // AUSTRALIA & OCEANIA
  "Australia":                { flag: "Australia.png",                      continent: "oceania",      display: "Australia" },
  "Fiji":                     { flag: "Fiji.png",                            continent: "oceania",      display: "Fiji" },
  "Kiribati":                 { flag: "Kiribati.png",                       continent: "oceania",      display: "Kiribati" },
  "Marshall Islands":         { flag: "Marshall Islands.png",               continent: "oceania",      display: "Marshall Islands" },
  "Micronesia, Fed. Sts.":    { flag: "Micronesia Federated States.png",    continent: "oceania",      display: "Micronesia" },
  "Micronesia":               { flag: "Micronesia Federated States.png",    continent: "oceania",      display: "Micronesia" },
  "Nauru":                    { flag: "Nauru.png",                          continent: "oceania",      display: "Nauru" },
  "New Caledonia":             { flag: "France.png",                         continent: "oceania",      display: "New Caledonia" },
  "New Zealand":              { flag: "New Zealand.png",                    continent: "oceania",      display: "New Zealand" },
  "Palau":                    { flag: "Palau.png",                          continent: "oceania",      display: "Palau" },
  "Papua New Guinea":         { flag: "Papua New Guinea.png",               continent: "oceania",      display: "Papua New Guinea" },
  "Samoa":                    { flag: "Samoa.png",                          continent: "oceania",      display: "Samoa" },
  "Solomon Is.":              { flag: "Solomon Islands.png",                continent: "oceania",      display: "Solomon Islands" },
  "Solomon Islands":          { flag: "Solomon Islands.png",                continent: "oceania",      display: "Solomon Islands" },
  "Tonga":                    { flag: "Tonga.png",                          continent: "oceania",      display: "Tonga" },
  "Tuvalu":                   { flag: "Tuvalu.png",                         continent: "oceania",      display: "Tuvalu" },
  "Vanuatu":                  { flag: "Vanuatu.png",                        continent: "oceania",      display: "Vanuatu" },

  // SPECIAL TERRITORIES & DEPENDENCIES (shown on map)
  "Greenland":                { flag: "Greenland.png",                      continent: "northamerica", display: "Greenland" },
  "Fr. S. Antarctic Lands":   { flag: "French Southern and Antarctic Lands.png", continent: "oceania", display: "French Southern Lands" },
  "Antarctica":               { flag: "Antarctica.png",                     continent: "oceania",      display: "Antarctica" }
};

// Additional flags not on the main TopoJSON but available as PNGs
// These will appear in the sidebar country list
const EXTRA_FLAGS = [
  { name: "Abhkazia",            flag: "Abhkazia.png",            continent: "asia" },
  { name: "Adygea",              flag: "Adygea.png",              continent: "europe" },
  { name: "Ajaria",              flag: "Ajaria.png",              continent: "asia" },
  { name: "Åland Islands",       flag: "Aland.png",               continent: "europe" },
  { name: "Alderney",            flag: "Alderney.png",            continent: "europe" },
  { name: "Altai Republic",      flag: "Altai Republic.png",      continent: "asia" },
  { name: "American Samoa",      flag: "American Samoa.png",      continent: "oceania" },
  { name: "Anguilla",            flag: "Anguilla.png",            continent: "northamerica" },
  { name: "Aruba",               flag: "Aruba.png",               continent: "northamerica" },
  { name: "Bashkortostan",       flag: "Bashkortostan.png",       continent: "europe" },
  { name: "Bermuda",             flag: "Bermuda.png",             continent: "northamerica" },
  { name: "Bikini Atoll",        flag: "Bikini Atoll.png",        continent: "oceania" },
  { name: "British Antarctic Territory", flag: "British Antarctic Territory.png", continent: "oceania" },
  { name: "British Indian Ocean Territory", flag: "British Indian Ocean Territory.png", continent: "asia" },
  { name: "Brittany",            flag: "Brittany.png",            continent: "europe" },
  { name: "Buryatia",            flag: "Buryatia.png",            continent: "asia" },
  { name: "Cayman Islands",      flag: "Cayman Islands.png",      continent: "northamerica" },
  { name: "Chechen Republic",    flag: "Chechen Republic.png",    continent: "europe" },
  { name: "Christmas Island",    flag: "Christmas Island.png",    continent: "oceania" },
  { name: "Chuvashia",           flag: "Chuvashia.png",           continent: "europe" },
  { name: "Cook Islands",        flag: "Cook Islands.png",        continent: "oceania" },
  { name: "Crimea",              flag: "Crimea.png",              continent: "europe" },
  { name: "Dagestan",            flag: "Dagestan.png",            continent: "europe" },
  { name: "Easter Island",       flag: "Easter Island Rapa Nui.png", continent: "southamerica" },
  { name: "England",             flag: "England.png",             continent: "europe" },
  { name: "European Union",      flag: "European Union.png",      continent: "europe" },
  { name: "Faroe Islands",       flag: "Faroe Island.png",        continent: "europe" },
  { name: "French Polynesia",    flag: "French Polynesia.png",    continent: "oceania" },
  { name: "Gibraltar",           flag: "Gibraltar.png",           continent: "europe" },
  { name: "Great Britain",       flag: "Great Britain.png",       continent: "europe" },
  { name: "Guam",                flag: "Guam.png",                continent: "oceania" },
  { name: "Guernsey",            flag: "Guernsey.png",            continent: "europe" },
  { name: "Herm",                flag: "Herm.png",                continent: "europe" },
  { name: "Ingushetia",          flag: "Ingushetia.png",          continent: "europe" },
  { name: "Isle of Man",         flag: "Isle of Man.png",         continent: "europe" },
  { name: "Jersey",              flag: "Jersey.png",              continent: "europe" },
  { name: "Kabardino-Balkaria",  flag: "Kabardino Balkaria.png",  continent: "europe" },
  { name: "Kalmykia",            flag: "Kalmykia.png",            continent: "europe" },
  { name: "Karachay-Cherkessia", flag: "Karachay Cherkessia.png", continent: "europe" },
  { name: "Karakalpakstan",      flag: "Karakalpakstan.png",      continent: "asia" },
  { name: "Karelia",             flag: "Karelia.png",             continent: "europe" },
  { name: "Khakassia",           flag: "Khakassia.png",           continent: "asia" },
  { name: "Komi",                flag: "Komi.png",                continent: "europe" },
  { name: "Ladonia",             flag: "Ladonia.png",             continent: "europe" },
  { name: "Los Altos",           flag: "Los Altos.png",           continent: "northamerica" },
  { name: "Mari El",             flag: "Mari El.png",             continent: "europe" },
  { name: "Montserrat",          flag: "Montserrat.png",          continent: "northamerica" },
  { name: "Mordovia",            flag: "Mordovia.png",            continent: "europe" },
  { name: "Nagorno-Karabakh",    flag: "Nagorno Karabakh Republic.png", continent: "asia" },
  { name: "Netherlands Antilles",flag: "Netherlands Antilles.png",continent: "northamerica" },
  { name: "Niue",                flag: "Niue.png",                continent: "oceania" },
  { name: "Norfolk Island",      flag: "Norfolk Island.png",      continent: "oceania" },
  { name: "North Ossetia",       flag: "North Ossetia.png",       continent: "europe" },
  { name: "Northern Ireland",    flag: "Northern ireland.png",    continent: "europe" },
  { name: "Northern Mariana Islands", flag: "Northern Mariana Islands.png", continent: "oceania" },
  { name: "Pitcairn Islands",    flag: "Pitcairn Islands.png",    continent: "oceania" },
  { name: "Saba",                flag: "Saba.png",                continent: "northamerica" },
  { name: "Saint Barthélemy",    flag: "Saint Barthelemy.png",     continent: "northamerica" },
  { name: "Saint Helena",        flag: "Saint Helena.png",        continent: "africa" },
  { name: "Saint Martin",        flag: "Saint Martin.png",        continent: "northamerica" },
  { name: "Saint Pierre and Miquelon", flag: "Saint Pierre and Miquelon.png", continent: "northamerica" },
  { name: "Sakha Republic",      flag: "Sakha Republic.png",      continent: "asia" },
  { name: "Sark",                flag: "Sark.png",                continent: "europe" },
  { name: "Scotland",            flag: "Scotland.png",            continent: "europe" },
  { name: "Sealand",             flag: "Sealand Principality of.png", continent: "europe" },
  { name: "Sikkim",              flag: "Sikkim.png",              continent: "asia" },
  { name: "South Georgia",       flag: "South Georgia and the South Sandwich Islands.png", continent: "southamerica" },
  { name: "South Ossetia",       flag: "South Ossetia.png",       continent: "asia" },
  { name: "Sovereign Military Order of Malta", flag: "Sovereign Military Order of Malta.png", continent: "europe" },
  { name: "Tatarstan",           flag: "Tatarstan.png",           continent: "europe" },
  { name: "Tierra del Fuego",    flag: "Tierra del Fuego Province Argentina.png", continent: "southamerica" },
  { name: "Tokelau",             flag: "Tokelau.png",             continent: "oceania" },
  { name: "Transnistria",        flag: "Transnistria.png",        continent: "europe" },
  { name: "Tristan da Cunha",    flag: "Tristan da Cunha.png",    continent: "africa" },
  { name: "Turks and Caicos Islands", flag: "Turks and Caicos Islands.png", continent: "northamerica" },
  { name: "Tuva",                flag: "Tuva.png",                continent: "asia" },
  { name: "Udmurtia",            flag: "Udmurtia.png",            continent: "europe" },
  { name: "Vatican City",        flag: "Vatican City Holy See.png", continent: "europe" },
  { name: "Virgin Islands (UK)", flag: "Virgin Islands UK.png",   continent: "northamerica" },
  { name: "Virgin Islands (US)", flag: "Virgin Islands US.png",   continent: "northamerica" },
  { name: "Wales",               flag: "Wales.png",               continent: "europe" },
  { name: "Samen",               flag: "Samen.png",               continent: "europe" }
];

// Build a unified list for the sidebar (countries + extras), removing duplicates
function buildFullCountryList() {
  const seen = new Set();
  const list = [];

  // Countries from the map data
  for (const [key, data] of Object.entries(COUNTRIES_DATA)) {
    const name = data.display;
    if (seen.has(name)) continue;
    seen.add(name);
    list.push({
      name: name,
      flag: data.flag,
      continent: data.continent,
      topoName: key,
      isOnMap: true
    });
  }

  // Extra flags
  for (const item of EXTRA_FLAGS) {
    if (seen.has(item.name)) continue;
    seen.add(item.name);
    list.push({
      name: item.name,
      flag: item.flag,
      continent: item.continent,
      topoName: null,
      isOnMap: false
    });
  }

  // Sort alphabetically
  list.sort((a, b) => a.name.localeCompare(b.name));
  return list;
}

function getFlagPath(flagFilename) {
  return `${FLAG_FOLDER}/${flagFilename}`;
}
